name: Kind
on: [push, pull_request]
jobs:
  test-unit:
    name: Sync secrets on kind 
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Build controller
      run: |
        go build -o bin/secret-replication-controller .
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster
    - name: Run some sanity checks
      run: |
        set -x
        ./bin/secret-replication-controller --kubeconfig ~/.kube/config &
        kubectl apply -f tests/e2e/testdata/replicate-all-registry-secret.yaml
        sleep 10
        secret_name=$(kubectl get events -o=jsonpath='{.items[0].involvedObject.name}')
        echo "The event is for $secret_name"
        if [ "$secret_name" != "gitlab-registry" ]; then
            exit 1
        fi
